apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tracking-server
  name: tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tracking-server
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: tracking-server
    spec:
      containers:
      - name: mlflow-server
        # image: dp.apps.rancher.io/containers/mlflow:3.3.2
        image: ghcr.io/mlflow/mlflow:v3.3.2
        command: ["/bin/sh"]
        args: ["-c", "apt-get update && apt-get install -y build-essential libpq-dev && pip install psycopg2 boto3 && mlflow server --backend-store-uri postgresql://mlflow:mlflow@susai-postgresql.suseai.svc.cluster.local:5432/mlflow --host 0.0.0.0 --serve-artifacts --artifacts-destination http://suseai-minio.suseai.svc.cluster.local:9000/mlflow"]         
        env:
          - name: AWS_ACCESS_KEY_ID
            value: mZNezGKCWJXFVmL84LCP
          - name: AWS_SECRET_ACCESS_KEY
            value: r6lPIWiniaZqWFzpihcFlNrlWkodtjzPujYzItVw
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://suseai-minio.suseai.svc.cluster.local:9000
          - name: MLFLOW_S3_IGNORE_TLS
            value: "true"
        livenessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:5000/
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort: 5000
            protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: application-collection