apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: suseai
spec:
  selector:
    app: tracking-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP # Or ClusterIP if you don't need external access
